### ISSUE TITLE
把webapp应用到微信公众号上

### ISSUE THREAD

**Issue by wenpi** [cloudenergy/webapp#1]
把webapp应用到微信公众号智慧云能源上，更改原有菜单，把前两项菜单合并更改为 物业中心  直接链接webapp，保留我的用电   账号绑定 链接绑定页面， 我的用电  链接消耗账单界面，充值缴费 链接充值界面

**Comment by realmx** [comment]
Issue moved to [cloudenergy/webapp-source #5](https://github.com/cloudenergy/webapp-source/issues/5) via [**ZenHub**](https://www.zenhub.com/)
